



# try:
#     a = 10
#     b = "20"
#     summ = a + b

#     print(summ)

# except Exception as e:
#     print(e)


# print("i am after error.... ")










